### ISSUE TITLE
Package name does not meet the idiomatic style guidelines for Go

### ISSUE THREAD

**Issue by bnarang** [angelbroking-github/smartapigo#2]
I was recently looking at this package out of my own interest in smart-api support by angel broking. Found that package name  does not seem to might the guideline of idiomatic Go

From the Go blog: https://blog.golang.org/package-names

```
The style of names typical of another language might not be idiomatic in a Go program. Here are two examples of names that might be good style in other languages but do not fit well in Go:

computeServiceClient
priority_queue
```
Looking forward to hearing the views

**Comment by ankush-ab** [comment]
Thanks for pointing out. I have changed the package name according to the go package naming convention. Closing this issue as it has been resolved now. Keep sharing your view it will help us in improving :)
