### ISSUE TITLE
LTP Data Struct Changes

### ISSUE THREAD

**Issue by akshaynavale20** [angelbroking-github/smartapigo#7]
Hi, one of your API for getting LTP data has ltp type of string in struct however API returning it with float64 so the struct facing an issue for binding different data types

Currently market.go has LTPResponse Data structure like this:

type LTPResponse struct {
	Exchange string `json:"exchange"`
	TradingSymbol string `json:"tradingsymbol"`
	SymbolToken string `json:"symboltoken"`
	Open string `json:"open"`
	High string `json:"high"`
	Low string `json:"low"`
	Close string `json:"close"`
	Ltp string `json:"ltp"`
}

Expected struct :

type LTPResponse struct {
	Exchange      string  `json:"exchange"`
	TradingSymbol string  `json:"tradingsymbol"`
	SymbolToken   string  `json:"symboltoken"`
	Open          float64 `json:"open"`
	High          float64 `json:"high"`
	Low           float64 `json:"low"`
	Close         float64 `json:"close"`
	Ltp           float64 `json:"ltp"`
}

**Comment by viveksingh-ab** [comment]
corrected LTPResponse struct hence closing the issue.
